apiVersion: v1
kind: Service
metadata:
  name: green-website
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: green
---
apiVersion: v1
kind: Service
metadata:
  name: blue-website
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: blue
